version: '3'

services:
  web:
    image: python:3.9
    depends_on:
      - db
    volumes:
      - .:/opt/timetable-bot
    container_name: timetable-web
    ports:
      - "0.0.0.0:8311:8000"
    env_file: .env
    working_dir: /opt/timetable-bot
    command: /bin/bash -c 'scripts/run-django.sh'

  # aiogram:
  #   image: python:3.9
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/opt/timetable-bot
  #   container_name: timetable-bot
  #   ports:
  #     - "0.0.0.0:8311:8000"
  #   env_file: .env
  #   working_dir: /opt/timetable-bot
  #   command: /bin/bash -c 'scripts/run-aiogram.sh'

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: timetable-db
    env_file: .env
    ports:
      - 5435:5432
